apiVersion: apps/v1
kind: Deployment
metadata:
  name: trackml-serve
  namespace: kubeflow
  labels:
    app: trackml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trackml
  template:
    metadata:
      labels:
        app: trackml
    spec:
      containers:
      - name: trackml-serve
        image: redis:5.0.3-alpine
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
---
apiVersion: v1
kind: Service
metadata:
  name: trackml-serve
  namespace: kubeflow
  labels:
    app: trackml
spec:
  ports:
  - name: trackml-serve
    port: 6379
    targetPort: 6379
  selector:
    app: trackml

